version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-alpine
    volumes:
      - /var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - account-network

  account-service:
    container_name: account-service
    build: .
    environment:
      PORT_HTTP: ${PORT_HTTP}
      RABBITMQ_HOST: rabbitmq
    ports:
      - 3001:3001
    depends_on:
      - rabbitmq
    volumes:
      - .:/home/account-service
    networks:
      - account-network

networks:
  account-network:
